version: '3'

services:
  sungwook.dev:
    container_name: sungwook.dev
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/app # 현재 디렉토리를 컨테이너의 /app에 마운트
      - /app/node_modules # node_modules를 제외
    ports:
      - '8080:8080'
    env_file:
      - ./env/.env

volumes:
  node_modules:
