version: '3'

services:
  sungwook-backend:
    container_name: sungwook-backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - backend_node_modules:/app/node_modules
      - ./env:/app/env
    networks:
      - internal
    ports:
      - '4000:4000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c 'pnpm install && pnpm run dev'

networks:
  internal:

volumes:
  backend_node_modules:
