name: Upload Backend to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-22.04

    env:
      DEPLOY_FILENAME: ${{ secrets.BACKEND_DEPLOY_FILENAME }}
      DEFAULT_BUCKET_REGION: ${{ secrets.DEFAULT_BUCKET_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET_BACKEND }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DEFAULT_BUCKET_REGION }}

      - name: Zip backend files
        run: zip -r $DEPLOY_FILENAME ./backend

      - name: List files (for debugging)
        run: ls -l

      - name: Deploy code to AWS S3
        run: aws s3 cp ./$DEPLOY_FILENAME s3://$S3_BUCKET --region $DEFAULT_BUCKET_REGION
