name: Upload Frontend to S3

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEFAULT_BUCKET_REGION: ${{ secrets.DEFAULT_BUCKET_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create .env file
        run: |
          mkdir -p ./frontend/env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> ./frontend/env/.env
          echo "VITE_TEST=${{ secrets.VITE_TEST }}" >> ./frontend/env/.env

      - name: Waiting build using Docker Compose
        run: |
          docker compose -f ./frontend/docker-compose.prod.yml up -d
          docker compose -f ./frontend/docker-compose.prod.yml logs -f

      - name: Copy built files to ./dist
        run: |
          mkdir -p ./dist
          cp -r ./frontend/dist/* ./dist/

      - name: Install AWS
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Upload to S3
        run: |
          aws s3 sync ./frontend/dist s3://$S3_BUCKET --region $DEFAULT_BUCKET_REGION --exclude "cdn/*" --exclude "fonts/*"
          aws s3 cp --cache-control 'max-age=300, stale-if-error=86400' ./frontend/dist/index.html s3://$S3_BUCKET --region $DEFAULT_BUCKET_REGION

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --region $DEFAULT_BUCKET_REGION --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
